name: mobile
description: "Çözüm Var - MVVM Architecture ile geliştirilmiş vatandaş bildirim uygulaması"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.1.3 <4.0.0"
  flutter: ">=3.1.3"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  
  # Temel Mimari Bileşenleri
  equatable: ^2.0.5
  get_it: ^8.0.0
  flutter_bloc: ^8.1.6
  
  # Ağ ve Veri Katmanı
  dio: ^5.4.0
  retrofit: ^4.1.0
  
  # UI ve Navigasyon
  auto_route: ^9.2.2
  google_fonts: ^6.1.0
  
  # Yerelleştirme
  easy_localization: ^3.0.3
  
  # Güvenli Depolama
  flutter_secure_storage: ^9.2.2
  
  # Medya ve Dosyalar
  image_picker: ^1.0.4
  cached_network_image: ^3.3.1
  permission_handler: ^11.0.1
  
  # Konum Servisleri
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Harita
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # UI Yardımcıları
  loading_animation_widget: ^1.2.0+4
  fluttertoast: ^8.2.4
  
  # Yardımcı Araçlar
  logger: ^2.0.2+1
  intl: ^0.20.2
  
  # Modüller
  widgets:
    path: module/widgets
  gen:
    path: module/gen
  common:
    path: module/common
  core:
    path: module/core
  json_annotation: ^4.9.0
  shimmer: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
  auto_route_generator: ^9.0.0
  retrofit_generator: ^8.1.0
  build_runner: ^2.4.7
  json_serializable: ^6.7.1
  mockito: ^5.4.4
  bloc_test: ^9.1.5
  flutter_launcher_icons: ^0.14.1
  device_preview: ^1.1.0
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true
  
  assets:
    - asset/translations/
    - asset/images/
    - asset/icons/
  

flutter_native_splash:
  color: "#1976D2"
  color_dark: "#0D47A1"
  android_12:
    color: "#1976D2"
    color_dark: "#0D47A1"
